### ISSUE TITLE
inference time

### ISSUE THREAD

**Issue by weidezhang** [uber-research/LaneGCN#12]
Sorry I just post a random question here. It appears every object need to go through the network once to predict trajectory. I am wondering about the online inference time of your network (maybe after onnx). Say if you have 20 objects in the map, can that be done in real time (say within couple of mili-seconds)?

**Comment by kaikaishen** [comment]
I am deploying model to C++ Project.Welcome to exchange.

**Comment by chenyuntc** [comment]
Hi @weidezhang, that's more like engineering. We didn't try that.

**Comment by weidezhang** [comment]
thx
