### ISSUE TITLE
How can I get the results in the Table 1 of the paper?

### ISSUE THREAD

**Issue by LaLaLailalai** [uber-research/LaneGCN#17]
I run this command: python test.py -m lanegcn --weight=/absolute/path/to/36.000.ckpt --split=test, but nothing printed except this: 
`2442it [15:14,  2.67it/s]^[[B^[[B
78143/78143--Return--
None
> /laneGCN/test.py(114)main()
    113         generate_forecasting_h5(preds, f"{config['save_dir']}/submit.h5")  # this might take awhile
--> 114     import ipdb;ipdb.set_trace()
    115 `

**Comment by LaLaLailalai** [comment]
fixed

**Comment by huanmanlou** [comment]
hi,may I ask how you solve this problem?
