### ISSUE TITLE
AttributeError: 'RandomSampler' object has no attribute 'set_epoch'

### ISSUE THREAD

**Issue by SHITIANYU-hue** [uber-research/LaneGCN#26]
When i run:

python train1.py -m lanegcn.  it will have this issue:

<img width="649" alt="image" src="https://user-images.githubusercontent.com/38762389/158665758-50279dd6-14f4-4ad8-a514-1624db55ff06.png">

**Comment by SHITIANYU-hue** [comment]
@chenyuntc

**Comment by chenyuntc** [comment]
Hi @SHITIANYU-hue. You may remove this line code. This is for shuffle in distributed training.
Sorry for the inconvenience.
Feel free to reopen it if you still have issues.
