### ISSUE TITLE
How can I get the results about test dataset

### ISSUE THREAD

**Issue by noparkee** [uber-research/LaneGCN#28]
I can get result about val dataset by running command: python test.py -m=lanegcn --weight=[ckpt PATH] --split=val --preprocess=True

but when I runned this command
```shell
python test.py -m=lanegcn --weight=[ckpt PATH] --split=val --preprocess=True
```
nothing printed. How can I get results about test dataset?

**Comment by noparkee** [comment]
I think that I can get the results only by submitting *.h5 files to the competition (https://eval.ai/challenge/454/leaderboard/1279)

**Comment by huanmanlou** [comment]
hi！Do you have a solution to this problem? Is it necessary to submit h5 files
