### ISSUE TITLE
Evaluation results mismatch raw source file

### ISSUE THREAD

**Issue by zhaone** [uber-research/LaneGCN#4]
Recently I wanna visualize your prediction result but I got a little confused about the correspondence between the idx of preprocessed val data and `$ARGO_RAW_DATA/val/data/argo_id.csv`.
In `ArgoTestDataset` :
https://github.com/uber-research/LaneGCN/blob/7e9b51d18a62f5dafb67a2215eba9053a64aff16/data.py#L382 
I download your **preprocessed val data** and found the **prediction paths with `argo_id` doesn't match the source file `$ARGO_RAW_DATA/val/data/argo_id.csv`.** My dataset source data is download from argo website(version 1.1), I want to know whether the order of preprocessed data matches `argo_id`? Or did I do something wrong?

**Comment by anant-joshi** [comment]
I tried this a few days back. There's a mismatch in the argo IDs for sure, but running the preprocessing script myself fixed the issue.

**Comment by chenyuntc** [comment]
Thanks for point out, will fix it after cvpr deadline

**Comment by zhaone** [comment]
Hi, may I ask whether you have upload newer matched preprocessed data? For me, due to the memory limitation, processing locally is sticky, even on the servers... Thank you 😄

**Comment by leoncesc** [comment]
When I run preprocess_data.py, "IndexError: list assignment index out of range" is encountered at the preprocessing validation dataset. The list variable `stores` is initialized as a fixed-length list, and the predefined length is not enough for validation data apparently.
Are other vehicles used during training not only the predicted agent vehicle but also other vehicles?

**Comment by leoncesc** [comment]
Are other vehicles used during training not only the predicted agent vehicle but also other vehicles?

**Comment by Kay1794** [comment]
> I tried this a few days back. There's a mismatch in the argo IDs for sure, but running the preprocessing script myself fixed the issue.

Hi, thank you for your comments! I tried to preprocess data using the script they provided but still was not able to generated correct evaluation submission file. I was wondering when you preprocessed the data, did you directly run their script?

**Comment by chenyuntc** [comment]
Sorry for the late response here. I have been distracted since I left Uber.

I check the code, it seems that the `idx` and `argo_idx` mismatch because the [`ArgoVerseForcastingLoader` returns files in an inconsistent order (`os.listdir`)](https://github.com/argoai/argoverse-api/blob/b1730f9e4377325436f3364abb4c1fe54ec71b0a/argoverse/data_loading/argoverse_forecasting_loader.py#L37), which means it could be different in different machines.

Therefore I update the `data.py` in [this commit](https://github.com/uber-research/LaneGCN/commit/82e1bcc4206c4752833cae250dd61ad67db9dffb). Hope this can fix the bug.

You need to rerun the `preprocess_data.py` or wait for me to update the preprocessed data. I will update here after the latest data is uploaded.

**Comment by Kay1794** [comment]
> Sorry for the late response here. I have been distracted since I left Uber.
> 
> I check the code, it seems that the `idx` and `argo_idx` mismatch because the [`ArgoVerseForcastingLoader` returns files in an inconsistent order (`os.listdir`)](https://github.com/argoai/argoverse-api/blob/b1730f9e4377325436f3364abb4c1fe54ec71b0a/argoverse/data_loading/argoverse_forecasting_loader.py#L37), which means it could be different in different machines.
> 
> Therefore I update the `data.py` in [this commit](https://github.com/uber-research/LaneGCN/commit/82e1bcc4206c4752833cae250dd61ad67db9dffb). Hope this can fix the bug.
> 
> You need to rerun the `preprocess_data.py` or wait for me to update the preprocessed data. I will update here after the latest data is uploaded.

Thank you so much for the reply! I will do as you suggested. Hopefully it'll work :)

**Comment by Kay1794** [comment]
> Sorry for the late response here. I have been distracted since I left Uber.
> 
> I check the code, it seems that the `idx` and `argo_idx` mismatch because the [`ArgoVerseForcastingLoader` returns files in an inconsistent order (`os.listdir`)](https://github.com/argoai/argoverse-api/blob/b1730f9e4377325436f3364abb4c1fe54ec71b0a/argoverse/data_loading/argoverse_forecasting_loader.py#L37), which means it could be different in different machines.
> 
> Therefore I update the `data.py` in [this commit](https://github.com/uber-research/LaneGCN/commit/82e1bcc4206c4752833cae250dd61ad67db9dffb). Hope this can fix the bug.
> 
> You need to rerun the `preprocess_data.py` or wait for me to update the preprocessed data. I will update here after the latest data is uploaded.

It worked! I just simply pulled the repo and reran the preprocess_data.py. Thank you so much!

**Comment by chenyuntc** [comment]
Preprocessed test pickled updated. Let me know if you still have issues.

**Comment by chenyuntc** [comment]
Note that, I only update preprocessed test split. You need to reprocess val/train if you want to get correct mapping between `idx` and `argo_id` in that split.
