### ISSUE TITLE
how to visualization

### ISSUE THREAD

**Issue by mumian0822** [uber-research/LaneGCN#5]
Your work has been a great help for a beginner, but I don’t understand how to visualize the results obtained? Where are the imported cv2 modules used? Hope to get your reply, thank you again for your work.

**Comment by chenyuntc** [comment]
It's basically `plt.plot` and `plt.scatter`. But I haven't got time to clean this part of code.

**Comment by walterchenchn** [comment]
@mumian0822 how can you use 'preprocess_data.py'? I cost 5 hours but there is noting output. The cpu occupancy rate is high but gpu is low

**Comment by changer707** [comment]
Hi! I am really interested in your work, but there is no visualization module in your code. Could you please push the visualization part ? I will really appreciate it. Hope for your reply!

**Comment by chengshuai** [comment]
@chenyuntc Could you please push the visualization part ? I will really appreciate it. Hope for your reply!

**Comment by wanglaotou** [comment]
@chenyuntc Could you please push the visualization part ? I will really appreciate it. Hope for your reply!
